# coding: utf-8

"""
    Pybossa API

    API for the Pybossa project  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@scifabric.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def api_favorites_get(self, oid, **kwargs):  # noqa: E501
        """GET all tasks favorited by the current user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_favorites_get(oid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str oid: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.api_favorites_get_with_http_info(oid, **kwargs)  # noqa: E501
        else:
            (data) = self.api_favorites_get_with_http_info(oid, **kwargs)  # noqa: E501
            return data

    def api_favorites_get_with_http_info(self, oid, **kwargs):  # noqa: E501
        """GET all tasks favorited by the current user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_favorites_get_with_http_info(oid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str oid: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['oid']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_favorites_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'oid' is set
        if ('oid' not in params or
                params['oid'] is None):
            raise ValueError("Missing the required parameter `oid` when calling `api_favorites_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'oid' in params:
            path_params['oid'] = params['oid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/favorites', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_favorites_oid_get(self, oid, **kwargs):  # noqa: E501
        """GET all tasks favorited by the current user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_favorites_oid_get(oid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str oid: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.api_favorites_oid_get_with_http_info(oid, **kwargs)  # noqa: E501
        else:
            (data) = self.api_favorites_oid_get_with_http_info(oid, **kwargs)  # noqa: E501
            return data

    def api_favorites_oid_get_with_http_info(self, oid, **kwargs):  # noqa: E501
        """GET all tasks favorited by the current user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_favorites_oid_get_with_http_info(oid, async=True)
        >>> result = thread.get()

        :param async bool
        :param str oid: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['oid']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_favorites_oid_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'oid' is set
        if ('oid' not in params or
                params['oid'] is None):
            raise ValueError("Missing the required parameter `oid` when calling `api_favorites_oid_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'oid' in params:
            path_params['oid'] = params['oid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/favorites/{oid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_favorites_post(self, **kwargs):  # noqa: E501
        """POST a favourite task for the current user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_favorites_post(async=True)
        >>> result = thread.get()

        :param async bool
        :param TaskId task_id: The task ID to favorite
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.api_favorites_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.api_favorites_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def api_favorites_post_with_http_info(self, **kwargs):  # noqa: E501
        """POST a favourite task for the current user  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_favorites_post_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param TaskId task_id: The task ID to favorite
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['task_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_favorites_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'task_id' in params:
            body_params = params['task_id']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIKeyQueryParam']  # noqa: E501

        return self.api_client.call_api(
            '/api/favorites', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_result_get(self, palette, **kwargs):  # noqa: E501
        """Example endpoint returning a list of colors by palette  # noqa: E501

        In this example the specification is taken from external YAML file<br/>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_result_get(palette, async=True)
        >>> result = thread.get()

        :param async bool
        :param str palette: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.api_result_get_with_http_info(palette, **kwargs)  # noqa: E501
        else:
            (data) = self.api_result_get_with_http_info(palette, **kwargs)  # noqa: E501
            return data

    def api_result_get_with_http_info(self, palette, **kwargs):  # noqa: E501
        """Example endpoint returning a list of colors by palette  # noqa: E501

        In this example the specification is taken from external YAML file<br/>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_result_get_with_http_info(palette, async=True)
        >>> result = thread.get()

        :param async bool
        :param str palette: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['palette']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_result_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'palette' is set
        if ('palette' not in params or
                params['palette'] is None):
            raise ValueError("Missing the required parameter `palette` when calling `api_result_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'palette' in params:
            path_params['palette'] = params['palette']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/result', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def api_result_oid_get(self, palette, **kwargs):  # noqa: E501
        """Example endpoint returning a list of colors by palette  # noqa: E501

        In this example the specification is taken from external YAML file<br/>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_result_oid_get(palette, async=True)
        >>> result = thread.get()

        :param async bool
        :param str palette: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.api_result_oid_get_with_http_info(palette, **kwargs)  # noqa: E501
        else:
            (data) = self.api_result_oid_get_with_http_info(palette, **kwargs)  # noqa: E501
            return data

    def api_result_oid_get_with_http_info(self, palette, **kwargs):  # noqa: E501
        """Example endpoint returning a list of colors by palette  # noqa: E501

        In this example the specification is taken from external YAML file<br/>  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.api_result_oid_get_with_http_info(palette, async=True)
        >>> result = thread.get()

        :param async bool
        :param str palette: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['palette']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_result_oid_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'palette' is set
        if ('palette' not in params or
                params['palette'] is None):
            raise ValueError("Missing the required parameter `palette` when calling `api_result_oid_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'palette' in params:
            path_params['palette'] = params['palette']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/result/{oid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
