# coding: utf-8

"""
    Pybossa API

    API for the Pybossa project  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@scifabric.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_favorites_get(self):
        """Test case for api_favorites_get

        GET all tasks favorited by the current user  # noqa: E501
        """
        pass

    def test_api_favorites_oid_get(self):
        """Test case for api_favorites_oid_get

        GET all tasks favorited by the current user  # noqa: E501
        """
        pass

    def test_api_favorites_post(self):
        """Test case for api_favorites_post

        POST a favourite task for the current user  # noqa: E501
        """
        pass

    def test_api_result_get(self):
        """Test case for api_result_get

        Example endpoint returning a list of colors by palette  # noqa: E501
        """
        pass

    def test_api_result_oid_get(self):
        """Test case for api_result_oid_get

        Example endpoint returning a list of colors by palette  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
