# coding: utf-8

"""
    Pybossa API

    API for the Pybossa project  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@scifabric.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.task_id import TaskId  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskId(unittest.TestCase):
    """TaskId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskId(self):
        """Test TaskId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_id.TaskId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
