# coding: utf-8

"""
    Pybossa API

    API for the Pybossa project  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@scifabric.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tasks_api import TasksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_task_get(self):
        """Test case for api_task_get

        GET all tasks  # noqa: E501
        """
        pass

    def test_api_task_oid_get(self):
        """Test case for api_task_oid_get

        GET all tasks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
