# coding: utf-8

"""
    Pybossa API

    API for the Pybossa project  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@scifabric.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projects_api import ProjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_project_get(self):
        """Test case for api_project_get

        GET all projects  # noqa: E501
        """
        pass

    def test_api_project_oid_delete(self):
        """Test case for api_project_oid_delete

        DELETE an existing isntance of Project  # noqa: E501
        """
        pass

    def test_api_project_oid_get(self):
        """Test case for api_project_oid_get

        GET all projects  # noqa: E501
        """
        pass

    def test_api_project_oid_put(self):
        """Test case for api_project_oid_put

        Change an existing isntance of Project  # noqa: E501
        """
        pass

    def test_api_project_post(self):
        """Test case for api_project_post

        POST to create a project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
