# coding: utf-8

# flake8: noqa
"""
    Pybossa API

    API for the Pybossa project  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@scifabric.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.task_id import TaskId
